apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  minReadySeconds: 10
  replicas: 5
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
        - name: whatever
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
  selector:
    matchLabels:
      app: webapp-deployment