apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - port: 80
      name: http
      nodePort: 30080

  type: NodePort