apiVersion: v1
kind: Pod
metadata:
  name: mq-release-1
  labels:
    app: mq-release-1
    release: "1"
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-queue:release1